<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Testcontainers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Cassandra\Common.Cassandra.csproj" />
    <ProjectReference Include="..\Common.Kafka\Common.Kafka.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>
