apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-kibana
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}-kibana
spec:
  selector:
    app: {{.Release.Name}}-kibana
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{.Values.Kibana.Networking.AccessPort}}
