apiVersion: v1
kind: ConfigMap
metadata:
  name: backplane-kafka
  namespace: cecochat
  labels:
    app: backplane-kafka
data:
  entrypoint.sh: |-
    #!/bin/bash
    export KAFKA_BROKER_ID=${HOSTNAME##*-}
    /etc/confluent/docker/run
