<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="AuthService.proto" GrpcServices="All" />
    <Protobuf Include="Connection.proto" />
    <Protobuf Include="ConnectionCommandService.proto" GrpcServices="All" />
    <Protobuf Include="ConnectionQueryService.proto" GrpcServices="All" />
    <Protobuf Include="FileRef.proto" />
    <Protobuf Include="FileCommandService.proto" GrpcServices="All" />
    <Protobuf Include="FileQueryService.proto" GrpcServices="All" />
    <Protobuf Include="ProfileCommandService.proto" GrpcServices="All" />
    <Protobuf Include="ProfileFull.proto" />
    <Protobuf Include="ProfilePublic.proto" />
    <Protobuf Include="ProfileSearchResult.proto" />
    <Protobuf Include="ProfileUpdate.proto" />
    <Protobuf Include="ProfileQueryService.proto" GrpcServices="All" />
    <Protobuf Include="Registration.proto" />
  </ItemGroup>

</Project>

