<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Grpc.Net.ClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CecoChat.Chats.Contracts\CecoChat.Chats.Contracts.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>

