apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  serviceName: {{.Release.Name}}
  replicas: {{.Values.StatefulSet.Replicas}}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: {{.Values.Image.Name}}:{{.Values.Image.Tag}}
          imagePullPolicy: {{.Values.Image.PullPolicy}}
          ports:
            - containerPort: {{.Values.Networking.AccessPort}}
            - containerPort: {{.Values.Networking.ConsolePort}}
          env:
            - name: MINIO_ROOT_USER
              value: {{.Values.Access.RootUser}}
            - name: MINIO_ROOT_PASSWORD
              value: {{.Values.Access.RootPass}}
            - name: MINIO_VOLUMES
              value: /mnt/data
          volumeMounts:
            - name: data
              mountPath: /mnt/data
          command:
            - "/usr/bin/docker-entrypoint.sh"
          args:
            - "server"
            - "--console-address"
            - ":{{.Values.Networking.ConsolePort}}"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{.Values.Resources.Requests.Storage}}
