<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Calzolari.Grpc.AspNetCore.Validation" />
    <PackageReference Include="Calzolari.Grpc.Net.Client.Validation" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.GrpcNetClient" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Span" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CecoChat.Config/CecoChat.Config.csproj" />
    <ProjectReference Include="../Common.AspNet/Common.AspNet.csproj" />
    <ProjectReference Include="../Common.Kafka/Common.Kafka.csproj" />
    <ProjectReference Include="../Common.OpenTelemetry/Common.OpenTelemetry.csproj" />
  </ItemGroup>

</Project>
