apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}
data:
  {{.Values.Entrypoint.ConfigName}}: |-
    #!/bin/bash
    export CECOCHAT_Config__ServerId=${HOSTNAME##*-}
    dotnet CecoChat.Messaging.Service.dll
