apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: cecochat
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  type: ClusterIP
  ports:
    - port: 5775
      protocol: UDP
      name: "5775"
    - port: 5778
      name: "5778"
    - port: 6831
      protocol: UDP
      name: "6831"
    - port: 6832
      protocol: UDP
      name: "6832"
    - port: 9411
      name: "9411"
    - port: 14268
      name: "14268"
    - port: 16686
      name: "16686"
