StatefulSet:
  Replicas: 1
Image:
  Name: jaegertracing/all-in-one
  Tag: 1.47.0
  PullPolicy: IfNotPresent
Networking:
  Jaeger:
    OtlpOverGrpcPort: 4317
    ConfigsPort: 5778
    AccessPort: 16686
Ingress:
  Host: jaeger.cecochat.com
  SecretName: ingress-tls
