version: '3'
networks: 
  cecochat:
services:
  cassandra0:
    image: cassandra:4.1.3
    container_name: cecochat-cassandra0
    hostname: cassandra0
    networks: &networks
      - cecochat
    ports:
      - "9042:9042"
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck: &healthcheck
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      CASSANDRA_SEEDS: "cassandra0,cassandra1"
      CASSANDRA_CLUSTER_NAME: cecochat
      CASSANDRA_DC: Europe
      CASSANDRA_RACK: Rack0
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
      HEAP_NEWSIZE: 128M
      MAX_HEAP_SIZE: 512M
    volumes: 
      - cecochat-cassandra0-data:/var/lib/cassandra
      - cecochat-cassandra0-conf:/etc/cassandra
  cassandra1:
    image: cassandra:4.1.3
    container_name: cecochat-cassandra1
    hostname: cassandra1
    networks: *networks
    ports:
      - "9043:9042"
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck: *healthcheck
    environment:
      CASSANDRA_SEEDS: "cassandra0,cassandra1"
      CASSANDRA_CLUSTER_NAME: cecochat
      CASSANDRA_DC: Europe
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
      HEAP_NEWSIZE: 128M
      MAX_HEAP_SIZE: 512M
    volumes: 
      - cecochat-cassandra1-data:/var/lib/cassandra
      - cecochat-cassandra1-conf:/etc/cassandra
volumes:
  cecochat-cassandra0-data:
    external: true
  cecochat-cassandra0-conf:
    external: true
  cecochat-cassandra1-data:
    external: true
  cecochat-cassandra1-conf:
    external: true
