version: '3'
networks:
  cecochat:
services:
  cecochat-bff:
    image: ceco.com/cecochat/bff:0.1
    container_name: cecochat-bff
    hostname: bff
    networks: &networks
      - cecochat
    ports:
      - "31000:443"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_HistoryClient__Address: "https://history"
      CECOCHAT_StateClient__Address: "https://state"
      CECOCHAT_ConfigDB__Endpoints__0: "redis:6379"
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
    logging: &fluentd-logging
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: cecochat
  cecochat-messaging1:
    image: ceco.com/cecochat/messaging:0.1
    container_name: cecochat-messaging1
    hostname: messaging1
    networks: *networks
    ports:
      - "31001:443"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: "redis:6379"
      CECOCHAT_Config__ServerID: s1
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka1:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka2:19092
      CECOCHAT_IDGen__OriginatorID: 1
      CECOCHAT_IDGen__Address: "https://idgen"
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
    logging: *fluentd-logging
  cecochat-messaging2:
    image: ceco.com/cecochat/messaging:0.1
    container_name: cecochat-messaging2
    hostname: messaging2
    networks: *networks
    ports:
      - "31011:443"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: "redis:6379"
      CECOCHAT_Backplane__ServerID: s2
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka1:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka2:19092
      CECOCHAT_IDGen__OriginatorID: 2
      CECOCHAT_IDGen__Address: "https://idgen"
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
    logging: *fluentd-logging
  cecochat-state:
    image: ceco.com/cecochat/state:0.1
    container_name: cecochat-state
    hostname: state
    networks: *networks
    ports:
      - "31002:443"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_StateDB__ContactPoints__0: cass1
      CECOCHAT_StateDB__ContactPoints__1: cass2
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka1:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka2:19092
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
    logging: *fluentd-logging
  cecochat-history:
    image: ceco.com/cecochat/history:0.1
    container_name: cecochat-history
    hostname: history
    networks: *networks
    ports:
      - "31003:443"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: "redis:6379"
      CECOCHAT_HistoryDB__ContactPoints__0: cass1
      CECOCHAT_HistoryDB__ContactPoints__1: cass2
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka1:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka2:19092
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
    logging: *fluentd-logging
  cecochat-idgen:
    image: ceco.com/cecochat/idgen:0.1
    container_name: cecochat-idgen
    hostname: idgen
    networks: *networks
    ports:
      - "31004:443"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_Config__ServerID: "1"
      CECOCHAT_ConfigDB__Endpoints__0: "redis:6379"
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
    logging: *fluentd-logging
  cecochat-user:
    image: ceco.com/cecochat/user:0.1
    container_name: cecochat-user
    hostname: user
    networks: *networks
    ports:
      - "31005:443"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_UserDB__Init__ConnectionString: "Host=yb-tserver;Port=5433;Database=postgres;Username=yugabyte;Password=yugabyte;"
      CECOCHAT_UserDB__Seed: "true"
      CECOCHAT_UserDB__Connect__ConnectionString: "Host=yb-tserver;Port=5433;Database=users;Username=cecochat_dev;Password=secret;"
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
    logging: *fluentd-logging
