version: '3'
networks:
  cecochat:
services:
  cecochat-bff:
    image: ceco.com/cecochat/bff:0.1
    container_name: cecochat-bff
    hostname: bff
    networks: &networks
      - cecochat
    ports:
      - "31000:443"
    healthcheck: &healthcheck
      test: "curl --fail https://localhost/healthz || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_HistoryClient__Address: "https://history"
      CECOCHAT_UserClient__Address: "https://user"
      CECOCHAT_StateClient__Address: "https://state"
      CECOCHAT_ConfigDB__Endpoints__0: redis:6379
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
#    logging: &fluentd-logging
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: cecochat
  cecochat-messaging0:
    image: ceco.com/cecochat/messaging:0.1
    container_name: cecochat-messaging0
    hostname: messaging0
    networks: *networks
    ports:
      - "31001:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: redis:6379
      CECOCHAT_Config__ServerID: 0
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka0:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka1:19092
      CECOCHAT_IDGen__OriginatorID: 0
      CECOCHAT_IDGen__Address: "https://idgen"
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
#    logging: *fluentd-logging
  cecochat-messaging1:
    image: ceco.com/cecochat/messaging:0.1
    container_name: cecochat-messaging1
    hostname: messaging1
    networks: *networks
    ports:
      - "31011:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: redis:6379
      CECOCHAT_Backplane__ServerID: 1
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka0:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka1:19092
      CECOCHAT_IDGen__OriginatorID: 1
      CECOCHAT_IDGen__Address: "https://idgen"
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
#    logging: *fluentd-logging
  cecochat-state:
    image: ceco.com/cecochat/state:0.1
    container_name: cecochat-state
    hostname: state
    networks: *networks
    ports:
      - "31002:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: redis:6379
      CECOCHAT_StateDB__ContactPoints__0: cassandra0
      CECOCHAT_StateDB__ContactPoints__1: cassandra1
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka0:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka1:19092
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
#    logging: *fluentd-logging
  cecochat-history:
    image: ceco.com/cecochat/history:0.1
    container_name: cecochat-history
    hostname: history
    networks: *networks
    ports:
      - "31003:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: redis:6379
      CECOCHAT_HistoryDB__ContactPoints__0: cassandra0
      CECOCHAT_HistoryDB__ContactPoints__1: cassandra1
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka0:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka1:19092
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
#    logging: *fluentd-logging
  cecochat-idgen:
    image: ceco.com/cecochat/idgen:0.1
    container_name: cecochat-idgen
    hostname: idgen
    networks: *networks
    ports:
      - "31004:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_Config__ServerID: 0
      CECOCHAT_ConfigDB__Endpoints__0: redis:6379
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
#    logging: *fluentd-logging
  cecochat-user:
    image: ceco.com/cecochat/user:0.1
    container_name: cecochat-user
    hostname: user
    networks: *networks
    ports:
      - "31005:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_UserDB__Init__ConnectionString: "Host=yb-tserver0,yb-tserver1;Port=5433;Database=postgres;Username=yugabyte;Password=yugabyte;"
      CECOCHAT_UserDB__Seed: "true"
      CECOCHAT_UserDB__Connect__ConnectionString: "Host=yb-tserver0,yb-tserver1;Port=5433;Database=users;Username=cecochat_dev;Password=secret;"
      CECOCHAT_OtelSampling__Strategy: "AlwaysOn"
      CECOCHAT_Jaeger__AgentHost: jaeger
#    logging: *fluentd-logging
