version: '3'
networks:
  cecochat:
services:
  cecochat-idgen:
    image: ceco.com/cecochat/idgen:0.1
    container_name: cecochat-idgen
    hostname: idgen
    networks: &networks
      - cecochat
    ports:
      - "31002:443"
    healthcheck: &healthcheck
      test: "curl --fail https://localhost/healthz || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_Config__ServerId: 0
      CECOCHAT_ConfigClient__Address: "https://config"
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka0:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka1:19092
      CECOCHAT_Telemetry__Tracing__Sampling__Strategy: Probability
      CECOCHAT_Telemetry__Tracing__Sampling__Probability: 0.1
      CECOCHAT_Telemetry__Tracing__Export__TargetHost: otel-collector
      CECOCHAT_Telemetry__Tracing__Export__TargetPort: 4317
      CECOCHAT_Telemetry__Logging__Export__TargetHost: otel-collector
      CECOCHAT_Telemetry__Logging__Export__TargetPort: 4317
  cecochat-messaging0:
    image: ceco.com/cecochat/messaging:0.1
    container_name: cecochat-messaging0
    hostname: messaging0
    networks: *networks
    ports:
      - "31000:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_Config__ServerId: 0
      CECOCHAT_ConfigClient__Address: "https://config"
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka0:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka1:19092
      CECOCHAT_IdGenClient__Address: "https://idgen"
      CECOCHAT_IdGenClient__RefreshIdsCount: 1024
      CECOCHAT_Telemetry__Tracing__Sampling__Strategy: Probability
      CECOCHAT_Telemetry__Tracing__Sampling__Probability: 0.1
      CECOCHAT_Telemetry__Tracing__Export__TargetHost: otel-collector
      CECOCHAT_Telemetry__Tracing__Export__TargetPort: 4317
      CECOCHAT_Telemetry__Logging__Export__TargetHost: otel-collector
      CECOCHAT_Telemetry__Logging__Export__TargetPort: 4317
  cecochat-messaging1:
    image: ceco.com/cecochat/messaging:0.1
    container_name: cecochat-messaging1
    hostname: messaging1
    networks: *networks
    ports:
      - "31001:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_Config__ServerId: 1
      CECOCHAT_ConfigClient__Address: "https://config"
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka0:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka1:19092
      CECOCHAT_IdGenClient__Address: "https://idgen"
      CECOCHAT_IdGenClient__RefreshIdsCount: 1024
      CECOCHAT_Telemetry__Tracing__Sampling__Strategy: Probability
      CECOCHAT_Telemetry__Tracing__Sampling__Probability: 0.1
      CECOCHAT_Telemetry__Tracing__Export__TargetHost: otel-collector
      CECOCHAT_Telemetry__Tracing__Export__TargetPort: 4317
      CECOCHAT_Telemetry__Logging__Export__TargetHost: otel-collector
      CECOCHAT_Telemetry__Logging__Export__TargetPort: 4317
