version: '3'
networks:
  cecochat:
services:
  cecochat-idgen:
    image: ceco.com/cecochat/idgen:0.1
    container_name: cecochat-idgen
    hostname: idgen
    networks: &networks
      - cecochat
    ports:
      - "31004:443"
    healthcheck: &healthcheck
      test: "curl --fail https://localhost/healthz || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: redis:6379
      CECOCHAT_ConfigDB__ConnectRetry: 16
      CECOCHAT_ConfigDB__ConnectTimeout: 5000
      CECOCHAT_ConfigDB__KeepAlive: 2
      CECOCHAT_OtelSampling__Strategy: Probability
      CECOCHAT_OtelSampling__Probability: 0.1
      CECOCHAT_Jaeger__AgentHost: jaeger
      CECOCHAT_Jaeger__AgentPort: 6831
      CECOCHAT_Jaeger__ExportProcessorType: Batch
      CECOCHAT_Jaeger__BatchExportScheduledDelayMillis: 2000
      CECOCHAT_Config__ServerId: 0
#    logging: &fluentd-logging
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: cecochat
  cecochat-messaging0:
    image: ceco.com/cecochat/messaging:0.1
    container_name: cecochat-messaging0
    hostname: messaging0
    networks: *networks
    ports:
      - "31001:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: redis:6379
      CECOCHAT_ConfigDB__ConnectRetry: 16
      CECOCHAT_ConfigDB__ConnectTimeout: 5000
      CECOCHAT_ConfigDB__KeepAlive: 2
      CECOCHAT_OtelSampling__Strategy: Probability
      CECOCHAT_OtelSampling__Probability: 0.1
      CECOCHAT_Jaeger__AgentHost: jaeger
      CECOCHAT_Jaeger__AgentPort: 6831
      CECOCHAT_Jaeger__ExportProcessorType: Batch
      CECOCHAT_Jaeger__BatchExportScheduledDelayMillis: 2000
      CECOCHAT_Config__ServerID: 0
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka0:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka1:19092
      CECOCHAT_IdGen__Address: "https://idgen"
      CECOCHAT_IdGen__OriginatorId: 0
      CECOCHAT_IdGen__RefreshIdsCount: 1024
#    logging: *fluentd-logging
  cecochat-messaging1:
    image: ceco.com/cecochat/messaging:0.1
    container_name: cecochat-messaging1
    hostname: messaging1
    networks: *networks
    ports:
      - "31011:443"
    healthcheck: *healthcheck
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
      CECOCHAT_ConfigDB__Endpoints__0: redis:6379
      CECOCHAT_ConfigDB__ConnectRetry: 16
      CECOCHAT_ConfigDB__ConnectTimeout: 5000
      CECOCHAT_ConfigDB__KeepAlive: 2
      CECOCHAT_OtelSampling__Strategy: Probability
      CECOCHAT_OtelSampling__Probability: 0.1
      CECOCHAT_Jaeger__AgentHost: jaeger
      CECOCHAT_Jaeger__AgentPort: 6831
      CECOCHAT_Jaeger__ExportProcessorType: Batch
      CECOCHAT_Jaeger__BatchExportScheduledDelayMillis: 2000
      CECOCHAT_Config__ServerID: 1
      CECOCHAT_Backplane__Kafka__BootstrapServers__0: kafka0:19091
      CECOCHAT_Backplane__Kafka__BootstrapServers__1: kafka1:19092
      CECOCHAT_IdGen__Address: "https://idgen"
      CECOCHAT_IdGen__OriginatorId: 1
      CECOCHAT_IdGen__RefreshIdsCount: 1024
#    logging: *fluentd-logging
