version: '3'
networks:
  cecochat:
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: cecochat-es
    hostname: es
    networks: &networks
      - cecochat
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - cecochat-es-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: cecochat-kibana
    hostname: kibana
    networks: *networks
    ports:
      - "5601:5601"
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    volumes:
      - cecochat-kibana-data:/usr/share/kibana/data
    depends_on:
      - es
volumes:
  cecochat-es-data:
    external: true
  cecochat-kibana-data:
    external: true
