version: '3'
networks:
  cecochat:
services:
  rediscommander:
    image: rediscommander/redis-commander
    container_name: cecochat-rediscommander
    hostname: rediscommander
    networks:
      - cecochat
    ports:
      - "8082:8081"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - REDIS_HOSTS=redis0:redis0:6379,redis1:redis1:6379,redis2:redis2:6379
