version: '3'
networks:
  cecochat:
services:
  redis:
    image: redis:7.0.12
    container_name: cecochat-redis
    hostname: redis
    networks: &networks
      - cecochat
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 64M
    volumes:
      - ./redis/redis.conf:/redis.conf
      - cecochat-redis-data:/data
    command: [ "redis-server", "/redis.conf" ]
volumes:
  cecochat-redis-data:
    external: true
