version: '3'
services:
  redis0:
    image: redis:7.2.3
    container_name: cecochat-redis0
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 64M
    volumes:
      - ./redis/redis.conf:/redis.conf
      - cecochat-redis0-data:/data
    command:
      - redis-server
      - /redis.conf
      - port
      - "6379"
      - --cluster-announce-ip
      - "127.0.0.1"
      - --cluster-announce-port
      - "6379"
      - --cluster-announce-bus-port
      - "16379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "127.0.0.1", "-p", "6379", "PING" ]
      interval: 5s
      timeout: 5s
      retries: 10
  redis1:
    image: redis:7.2.3
    container_name: cecochat-redis1
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 64M
    volumes:
      - ./redis/redis.conf:/redis.conf
      - cecochat-redis1-data:/data
    command:
      - redis-server
      - /redis.conf
      - port
      - "6380"
      - --cluster-announce-ip
      - "127.0.0.1"
      - --cluster-announce-port
      - "6380"
      - --cluster-announce-bus-port
      - "16380"
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "127.0.0.1", "-p", "6380", "PING" ]
      interval: 5s
      timeout: 5s
      retries: 10
  redis2:
    image: redis:7.2.3
    container_name: cecochat-redis2
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 64M
    volumes:
      - ./redis/redis.conf:/redis.conf
      - cecochat-redis2-data:/data
    command:
      - redis-server
      - /redis.conf
      - port
      - "6381"
      - --cluster-announce-ip
      - "127.0.0.1"
      - --cluster-announce-port
      - "6381"
      - --cluster-announce-bus-port
      - "16381"
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "127.0.0.1", "-p", "6381", "PING" ]
      interval: 5s
      timeout: 5s
      retries: 10
  redis-cluster-setup:
    image: redis:7.2.3
    container_name: cecochat-redis-cluster-setup
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 64M
    entrypoint: "redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 --cluster-yes"
    depends_on:
      - redis0
      - redis1
      - redis2
volumes:
  cecochat-redis0-data:
    external: true
  cecochat-redis1-data:
    external: true
  cecochat-redis2-data:
    external: true
