version: '3'
networks:
  cecochat:
services:
  jaeger:
    image: jaegertracing/all-in-one:1.47.0
    container_name: cecochat-jaeger
    hostname: jaeger
    networks: &networks
      - cecochat
    ports:
      # not mapped since the otel collector is using the same port on localhost
      # while jaeger is being called by the otel collector within the docker network
      #- "4317:4317" # accept OTLP over gRPC
      - "5778:5778" # serve configs (e.g. sampling)
      - "16686:16686" # serve frontend
    deploy:
      resources:
        limits:
          memory: 128M
