version: '3'
networks:
  cecochat:
services:
  yb-master:
    image: yugabytedb/yugabyte:2.16.1.0-b50
    container_name: cecochat-yb-master
    hostname: yb-master
    networks: &networks
      - cecochat
    ports:
      - "7000:7000"
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      SERVICE_7000_NAME: yb-master
      POSTGRES_USER: cecochat
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: cecochat_users
    volumes:
      - cecochat-yb-master:/mnt/master
    command:
      [ "/home/yugabyte/bin/yb-master",
        "--fs_data_dirs=/mnt/master",
        "--master_addresses=yb-master:7100",
        "--rpc_bind_addresses=yb-master:7100",
        "--replication_factor=1"]
  yb-tserver:
    image: yugabytedb/yugabyte:2.16.1.0-b50
    container_name: cecochat-yb-tserver
    hostname: yb-tserver
    networks: *networks
    ports:
      - "5433:5433"
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: yb-tserver
    volumes:
      - cecochat-yb-tserver:/mnt/tserver
    command:
      [ "/home/yugabyte/bin/yb-tserver",
        "--fs_data_dirs=/mnt/tserver",
        "--start_pgsql_proxy",
        "--rpc_bind_addresses=yb-tserver:9100",
        "--tserver_master_addrs=yb-master:7100"]
    depends_on:
      - yb-master
volumes:
  cecochat-yb-master:
    external: true
  cecochat-yb-tserver:
    external: true
