Deployment:
  Replicas: 2
Image:
  Name: ceco.com/cecochat/chats
  Tag: 0.1
  PullPolicy: IfNotPresent
Networking:
  Port: 443
  ChatsDb:
    Host: cassandra
    Service: cassandra
    LocalDc: Europe
    SocketConnectTimeout: 00:00:05.0
    ExponentialReconnectPolicy: true
    ExponentialReconnectPolicyBaseDelay: 00:00:00.100
    ExponentialReconnectPolicyMaxDelay: 00:00:05.0
Probes:
  Scheme: HTTPS
