Deployment:
  Replicas: 2
Image:
  Name: ceco.com/cecochat/bff
  Tag: 0.1
  PullPolicy: IfNotPresent
Networking:
  Port: 443
  UserService: user
  ChatsService: chats
  FileStorage:
    Host: minio
    Service: minio
    Port: 9000
    AccessKey: admin
    Secret: secret12
Ingress:
  Host: bff.cecochat.com
  SecretName: ingress-tls
Probes:
  Scheme: HTTPS
