{
 "title": "http/db requests",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP request rate / 10m",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_duration_ms_count[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request duration ms",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "http_server_duration_ms_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "history db request rate / 10m",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(historydb_query_duration_ms_count[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "history db request duration ms",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "historydb_query_duration_ms_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "state db request rate / 10m",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(statedb_query_duration_ms_count[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "state db request duration ms",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "statedb_query_duration_ms_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}