{
 "title": "messaging",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "online clients total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(messaging_online_clients)", "legendFormat": "online clients" }
   ]
  },
  {
   "title": "online clients per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "messaging_online_clients",
     "legendFormat": "online clients (server {{messaging_server_id}})"
    }
   ]
  },
  {
   "title": "plain texts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(messaging_plain_texts_received)",
     "legendFormat": "received"
    },
    {
     "expr": "sum(messaging_plain_texts_processed)",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "plain texts received per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "messaging_plain_texts_received", "legendFormat": "server {{messaging_server_id}}" }
   ]
  },
  {
   "title": "plain texts processed per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "messaging_plain_texts_processed",
     "legendFormat": "server {{messaging_server_id}}"
    }
   ]
  },
  {
   "title": "reactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(messaging_reactions_received)",
     "legendFormat": "received"
    },
    {
     "expr": "sum(messaging_reactions_processed)",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "reactions received per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "messaging_reactions_received", "legendFormat": "server {{messaging_server_id}}" }
   ]
  },
  {
   "title": "reactions processed per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "messaging_reactions_processed", "legendFormat": "server {{messaging_server_id}}" }
   ]
  },
  {
   "title": "unreactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(messaging_unreactions_received)",
     "legendFormat": "received"
    },
    {
     "expr": "sum(messaging_unreactions_processed)",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "ureactions received per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "messaging_unreactions_received", "legendFormat": "server {{messaging_server_id}}" }
   ]
  },
  {
   "title": "unreactions processed per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "messaging_unreactions_processed",
     "legendFormat": "server {{messaging_server_id}}"
    }
   ]
  }
 ]
}