global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "cecochat"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    enable_http2: true
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:31000" # messaging-0
          - "host.docker.internal:31001" # messaging-1
          - "host.docker.internal:31002" # idgen
          - "host.docker.internal:31003" # bff
          - "host.docker.internal:31004" # chats
          - "host.docker.internal:31005" # user
