apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: cecochat
  labels:
    app: cassandra
spec:
  selector:
    app: cassandra
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9042
