apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: cecochat
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      name: redis
      namespace: cecochat
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: 128Mi
          volumeMounts:
            - name: redis
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis
        namespace: cecochat
        labels:
          app: redis
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 128Mi
