apiVersion: apps/v1
kind: Deployment
metadata:
  name: state
  namespace: cecochat
  labels:
    app: state
spec:
  selector:
    matchLabels:
      app: state
  replicas: 2
  template:
    metadata:
      name: state
      namespace: cecochat
      labels:
        app: state
    spec:
      containers:
        - name: state
          image: ceco.com/cecochat/state:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
          startupProbe:
            httpGet:
              path: /startupz
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /livez
              port: 443
              scheme: HTTPS
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 443
              scheme: HTTPS
            periodSeconds: 30
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: service-aspnet
            - configMapRef:
                name: service-configdb
            - configMapRef:
                name: service-backplane
            - configMapRef:
                name: service-tracing
          env:
            - name: CECOCHAT_StateDB__ContactPoints__0
              value: cassandra-0.cassandra.cecochat.svc.cluster.local
            - name: CECOCHAT_StateDB__ContactPoints__1
              value: cassandra-1.cassandra.cecochat.svc.cluster.local
