<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CecoChat.Messaging.Contracts\CecoChat.Messaging.Contracts.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>
