global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "cecochat"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    enable_http2: true
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:31001" # messaging 1
          - "host.docker.internal:31011" # messaging 2
          - "host.docker.internal:31000" # bff
          - "host.docker.internal:31002" # state
          - "host.docker.internal:31003" # history
          - "host.docker.internal:31004" # idgen
