apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-jaeger
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}-jaeger
spec:
  selector:
    app: {{.Release.Name}}-jaeger
  type: ClusterIP
  clusterIP: None
  ports:
    - name: "{{.Values.Networking.Jaeger.OtlpOverGrpcPort}}"
      port: {{.Values.Networking.Jaeger.OtlpOverGrpcPort}}
    - name: "{{.Values.Networking.Jaeger.ConfigsPort}}"
      port: {{.Values.Networking.Jaeger.ConfigsPort}}
    - name: "{{.Values.Networking.Jaeger.AccessPort}}"
      port: {{.Values.Networking.Jaeger.AccessPort}}
