apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: messaging
  namespace: cecochat
  labels:
    app: messaging
spec:
  selector:
    matchLabels:
      app: messaging
  serviceName: messaging
  replicas: 2
  template:
    metadata:
      name: messaging
      namespace: cecochat
      labels:
        app: messaging
    spec:
      containers:
        - name: messaging
          image: ceco.com/cecochat/messaging:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: service-aspnet
            - configMapRef:
                name: service-configdb
            - configMapRef:
                name: service-tracing
          env:
            # backplane
            - name: CECOCHAT_Backplane__Kafka__BootstrapServers__0
              value: backplane-kafka-0.backplane-kafka.cecochat.svc.cluster.local:9092
            - name: CECOCHAT_Backplane__Kafka__BootstrapServers__1
              value: backplane-kafka-1.backplane-kafka.cecochat.svc.cluster.local:9092
            # idgen
            - name: CECOCHAT_IDGen__Address
              value: https://idgen
          volumeMounts:
            - name: config
              mountPath: /bin/entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
          command:
            - /bin/entrypoint.sh
      volumes:
        - name: config
          configMap:
            name: messaging
            defaultMode: 0700
