apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  replicas: {{.Values.Deployment.Replicas}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: {{.Values.Image.Name}}:{{.Values.Image.Tag}}
          imagePullPolicy: {{.Values.Image.PullPolicy}}
          ports:
            - containerPort: {{.Values.Networking.Port}}
          startupProbe:
            httpGet:
              path: /startupz
              port: {{.Values.Networking.Port}}
              scheme: {{.Values.Probes.Scheme}}
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /livez
              port: {{.Values.Networking.Port}}
              scheme: {{.Values.Probes.Scheme}}
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{.Values.Networking.Port}}
              scheme: {{.Values.Probes.Scheme}}
            periodSeconds: 30
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: service-aspnet
            - configMapRef:
                name: service-backplane
            - configMapRef:
                name: service-tracing
            - configMapRef:
                name: service-logging
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # Config DB
            - name: CECOCHAT_ConfigDb__Init__ConnectionString
              value: Host={{.Values.Networking.ConfigDb.Host}}-0.{{.Values.Networking.ConfigDb.Service}}.$(NAMESPACE).svc.cluster.local;Port={{.Values.Networking.ConfigDb.Port}};Database=postgres;Username={{.Values.Networking.ConfigDb.Root.User}};Password={{.Values.Networking.ConfigDb.Root.Pass}};
            - name: CECOCHAT_ConfigDb__Connect__ConnectionString
              value: Host={{.Values.Networking.ConfigDb.Host}}-0.{{.Values.Networking.ConfigDb.Service}}.$(NAMESPACE).svc.cluster.local,{{.Values.Networking.ConfigDb.Host}}-1.{{.Values.Networking.ConfigDb.Service}}.$(NAMESPACE).svc.cluster.local;Port={{.Values.Networking.ConfigDb.Port}};Database=config;Username={{.Values.Networking.ConfigDb.Normal.User}};Password={{.Values.Networking.ConfigDb.Normal.Pass}};Keepalive=30;Load Balance Hosts=true;
            # Seed
            - name: CECOCHAT_ConfigDb__DeploymentEnvironment
              value: minikube
