apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backplane-zk
  namespace: cecochat
  labels:
    app: backplane
spec:
  selector:
    matchLabels:
      app: backplane
  serviceName: backplane-zk
  replicas: 2
  podManagementPolicy: Parallel
  template:
    metadata:
      name: backplane-zk
      namespace: cecochat
      labels:
        app: backplane
    spec:
      containers:
        - name: backplane-zk
          image: zookeeper:3.4.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          resources:
            limits:
              memory: 128Mi
          env:
            - name: ZOO_PORT
              value: "2181"
            - name: ZOO_SERVERS
              value: server.0=backplane-zk-0.backplane-zk.cecochat.svc.cluster.local:2888:3888 server.1=backplane-zk-1.backplane-zk.cecochat.svc.cluster.local:2888:3888
          volumeMounts:
            - name: config
              mountPath: /bin/entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
            - name: backplane-zk
              mountPath: /data
              subPath: data
            - name: backplane-zk
              mountPath: /datalog
              subPath: datalog
          command:
            - /bin/entrypoint.sh
      volumes:
        - name: config
          configMap:
            name: backplane-zk
            defaultMode: 0700
  volumeClaimTemplates:
    - metadata:
        name: backplane-zk
        namespace: cecochat
        labels:
          app: backplane
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 128Mi
