apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-otel-collector
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}-otel-collector
spec:
  selector:
    app: {{.Release.Name}}-otel-collector
  type: ClusterIP
  ports:
    - name: "{{.Values.Networking.OtlpOverGrpcPort}}"
      port: {{.Values.Networking.OtlpOverGrpcPort}}
