<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Contracts\BackplaneMessage.proto" />
    <Protobuf Include="Contracts\ConnectionStatus.proto" />
    <Protobuf Include="Contracts\DeliveryStatus.proto" />
    <Protobuf Include="Contracts\MessageType.proto" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Common.AspNet/Common.AspNet.csproj" />
    <ProjectReference Include="../Common.Kafka/Common.Kafka.csproj" />
  </ItemGroup>

</Project>
