apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jaeger
  namespace: cecochat
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  serviceName: jaeger
  replicas: 1
  template:
    metadata:
      name: jaeger
      namespace: cecochat
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.38.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 5778
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 9411
            - containerPort: 14268
            - containerPort: 16686
