<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <PackageReference Include="Grpc.Net.ClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CecoChat.IdGen.Contracts\CecoChat.IdGen.Contracts.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>
