apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: idgen
  namespace: cecochat
  labels:
    app: idgen
spec:
  selector:
    matchLabels:
      app: idgen
  serviceName: idgen
  replicas: 2
  template:
    metadata:
      name: idgen
      namespace: cecochat
      labels:
        app: idgen
    spec:
      containers:
        - name: idgen
          image: ceco.com/cecochat/idgen:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: service-aspnet
            - configMapRef:
                name: service-configdb
            - configMapRef:
                name: service-tracing
          volumeMounts:
            - name: config
              mountPath: /bin/entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
          command:
            - /bin/entrypoint.sh
      volumes:
        - name: config
          configMap:
            name: idgen
            defaultMode: 0700
