apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: idgen
  namespace: cecochat
  labels:
    app: idgen
spec:
  selector:
    matchLabels:
      app: idgen
  serviceName: idgen
  replicas: 2
  template:
    metadata:
      name: idgen
      namespace: cecochat
      labels:
        app: idgen
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: idgen
          image: ceco.com/cecochat/idgen:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
          startupProbe:
            httpGet:
              path: /startupz
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /livez
              port: 443
              scheme: HTTPS
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 443
              scheme: HTTPS
            periodSeconds: 30
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: service-aspnet
            - configMapRef:
                name: service-configdb
            - configMapRef:
                name: service-tracing
          volumeMounts:
            - name: config
              mountPath: /bin/entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
          command:
            - /bin/entrypoint.sh
      volumes:
        - name: config
          configMap:
            name: idgen
            defaultMode: 0700
