<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="ChatState.proto" />
    <Protobuf Include="DataType.proto" />
    <Protobuf Include="FileMessage.proto" />
    <Protobuf Include="PlainTextMessage.proto" />
    <Protobuf Include="HistoryMessage.proto" />
    <Protobuf Include="ChatsService.proto" GrpcServices="All" />
    <Protobuf Include="ReactionMessage.proto" />
  </ItemGroup>

</Project>
