CREATE TABLE IF NOT EXISTS public.profiles
(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 100 ),
    version timestamp with time zone NOT NULL,
    username text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    display_name text COLLATE pg_catalog."default" NOT NULL,
    avatar_url text COLLATE pg_catalog."default" NOT NULL,
    phone text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT profiles_pkey
        PRIMARY KEY (user_id),
    CONSTRAINT profiles_username_unique
        UNIQUE (username)
)
WITH
(
    OIDS = FALSE
)
TABLESPACE pg_default;

CREATE INDEX profiles_username_index
    ON public.profiles USING btree
        (username ASC NULLS LAST);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX profiles_username_trgm
    ON public.profiles USING gin
        (username gin_trgm_ops);

ALTER TABLE IF EXISTS public.profiles
    OWNER to yugabyte;
GRANT ALL ON TABLE public.profiles TO cecochat_dev;
GRANT ALL ON TABLE public.profiles TO yugabyte;
