apiVersion: v1
kind: ConfigMap
metadata:
  name: service-aspnet
  namespace: cecochat
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: https://+
  ASPNETCORE_HTTPS_PORT: "443"
  ASPNETCORE_Kestrel__Certificates__Default__Path: /app/services.pfx
  ASPNETCORE_Kestrel__Certificates__Default__Password: cecochat

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: service-configdb
  namespace: cecochat
data:
  CECOCHAT_ConfigDB__Endpoints__0: redis:6379

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: service-tracing
  namespace: cecochat
data:
  CECOCHAT_OtelSampling__Strategy: AlwaysOn
  CECOCHAT_Jaeger__AgentHost: jaeger
