apiVersion: v1
kind: ConfigMap
metadata:
  name: service-aspnet
  namespace: cecochat
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "https://+"
  ASPNETCORE_HTTPS_PORT: "443"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/services.pfx"
  ASPNETCORE_Kestrel__Certificates__Default__Password: "cecochat"
  DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config-client
  namespace: cecochat
data:
  CECOCHAT_ConfigClient__Address: "https://config"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: service-backplane
  namespace: cecochat
data:
  CECOCHAT_Backplane__Kafka__BootstrapServers__0: "backplane-kafka-0.backplane-kafka.cecochat.svc.cluster.local:9092"
  CECOCHAT_Backplane__Kafka__BootstrapServers__1: "backplane-kafka-1.backplane-kafka.cecochat.svc.cluster.local:9092"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: service-tracing
  namespace: cecochat
data:
  CECOCHAT_Telemetry__Tracing__Sampling__Strategy: "Probability"
  CECOCHAT_Telemetry__Tracing__Sampling__Probability: "0.1"
  CECOCHAT_Telemetry__Tracing__Export__TargetHost: "telemetry-otel-collector"
  CECOCHAT_Telemetry__Tracing__Export__TargetPort: "4317"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: service-logging
  namespace: cecochat
data:
  CECOCHAT_Telemetry__Logging__Export__TargetHost: "telemetry-otel-collector"
  CECOCHAT_Telemetry__Logging__Export__TargetPort: "4317"
