<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CassandraCSharpDriver" />
    <!-- Not used directly, but referenced explicitly since the Cassandra driver .nuspec file specifies and older version which contains security vulnerabilities -->
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Common/Common.csproj" />
    <ProjectReference Include="../Common.OpenTelemetry/Common.OpenTelemetry.csproj" />
  </ItemGroup>

</Project>
