<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CassandraCSharpDriver" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Common/Common.csproj" />
    <ProjectReference Include="../Common.OpenTelemetry/Common.OpenTelemetry.csproj" />
  </ItemGroup>

</Project>
