version: '3'
services:
  cass-web:
    image: markusgulden/cassandra-web
    container_name: cecochat-cassweb
    hostname: cassweb
    ports:
    - "3000:3000"
    mem_limit: 128M
    environment:
      CASSANDRA_HOST_IPS: 192.168.0.101
      CASSANDRA_PORT: 9042
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
