version: '3'
networks:
  cecochat:
services:
  profiledb-leader:
    image: mongo:4.4.3
    container_name: cecochat-profiledb-leader
    hostname: profiledb-leader
    networks: &networks
      - cecochat
    ports:
      - "27017:27017"
    mem_limit: 512M
    volumes:
      - cecochat-profiledb-leader-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
  profiledb-mongoexpress:
    image: mongo-express
    container_name: cecochat-profiledb-mongoexpress
    hostname: profiledb-mongoexpress
    networks: *networks
    ports:
      - 27000:8081
    mem_limit: 512M
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: profiledb-leader
volumes:
  cecochat-profiledb-leader-data:
    external: true
