version: '3'
networks:
  cecochat:
services:
  mongodb1:
    image: mongo:4.4.3
    container_name: cecochat-mongodb1
    hostname: mongodb1
    networks: &networks
      - cecochat
    ports:
      - "27017:27017"
    mem_limit: 256M
    volumes:
      - cecochat-mongodb1-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
  mongoexpress:
    image: mongo-express
    container_name: cecochat-mongoexpress
    hostname: mongoexpress
    networks: *networks
    ports:
      - 27000:8081
    mem_limit: 128M
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb1
volumes:
  cecochat-mongodb1-data:
    external: true
