version: '3'
networks:
  cecochat:
services:
  jaeger:
    image: jaegertracing/all-in-one:1.22
    container_name: cecochat-jaeger
    hostname: jaeger
    networks: &networks
      - cecochat
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    mem_limit: 128M
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: cecochat-es
    hostname: es
    networks: *networks
    ports:
      - 9200:9200
    mem_limit: 512M
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - cecochat-es1-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: cecochat-kibana
    hostname: kibana
    networks: *networks
    ports:
      - 5601:5601
    mem_limit: 128M
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    volumes:
      - ./observe/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es
volumes:
  cecochat-es1-data:
    external: true
