version: '3'
networks:
  cecochat:
services:
  redis1:
    image: redis:6.0.10
    container_name: cecochat-redis1
    hostname: redis1
    networks: &networks
      - cecochat
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 64M
    volumes:
      - ./redis/redis1.conf:/redis.conf
      - cecochat-redis1-data:/data
    command: [ "redis-server", "/redis.conf" ]
volumes:
  cecochat-redis1-data:
    external: true
