apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  replicas: {{.Values.Deployment.Replicas}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: {{.Values.Image.Name}}:{{.Values.Image.Tag}}
          imagePullPolicy: {{.Values.Image.PullPolicy}}
          ports:
            - containerPort: {{.Values.Networking.Port}}
          startupProbe:
            httpGet:
              path: /startupz
              port: {{.Values.Networking.Port}}
              scheme: {{.Values.Probes.Scheme}}
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /livez
              port: {{.Values.Networking.Port}}
              scheme: {{.Values.Probes.Scheme}}
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{.Values.Networking.Port}}
              scheme: {{.Values.Probes.Scheme}}
            periodSeconds: 30
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: service-aspnet
            - configMapRef:
                name: service-config-client
            - configMapRef:
                name: service-backplane
            - configMapRef:
                name: service-tracing
            - configMapRef:
                name: service-logging
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CECOCHAT_UserClient__Address
              value: https://{{.Values.Networking.UserService}}
            - name: CECOCHAT_ChatsClient__Address
              value: https://{{.Values.Networking.ChatsService}}
            - name: CECOCHAT_FileStorage__Endpoint
              value: "http://{{.Values.Networking.FileStorage.Host}}-0.{{.Values.Networking.FileStorage.Service}}.$(NAMESPACE).svc.cluster.local:{{.Values.Networking.FileStorage.Port}}"
            - name: CECOCHAT_FileStorage__AccessKey
              value: {{.Values.Networking.FileStorage.AccessKey}}
            - name: CECOCHAT_FileStorage__Secret
              value: {{.Values.Networking.FileStorage.Secret}}
