apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  replicas: {{.Values.Deployment.Replicas}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: {{.Values.Image.Name}}:{{.Values.Image.Tag}}
          imagePullPolicy: {{.Values.Image.PullPolicy}}
          ports:
            - containerPort: {{.Values.Networking.Port}}
          startupProbe:
            httpGet:
              path: /startupz
              port: {{.Values.Networking.Port}}
              scheme: {{.Values.Probes.Scheme}}
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /livez
              port: {{.Values.Networking.Port}}
              scheme: {{.Values.Probes.Scheme}}
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{.Values.Networking.Port}}
              scheme: {{.Values.Probes.Scheme}}
            periodSeconds: 30
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: service-aspnet
            - configMapRef:
                name: service-configdb
            - configMapRef:
                name: service-tracing
            - configMapRef:
                name: service-logging
          env:
            - name: CECOCHAT_UserClient__Address
              value: https://{{.Values.Networking.UserService}}
            - name: CECOCHAT_StateClient__Address
              value: https://{{.Values.Networking.StateService}}
            - name: CECOCHAT_HistoryClient__Address
              value: https://{{.Values.Networking.HistoryService}}
