<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CecoChat.IdGen.Client\CecoChat.IdGen.Client.csproj" />
    <ProjectReference Include="..\CecoChat.IdGen.Service\CecoChat.IdGen.Service.csproj" />
    <ProjectReference Include="..\CecoChat.Testing\CecoChat.Testing.csproj" />
    <ProjectReference Include="..\Common.Testing\Common.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\certificates\services.pfx" Link="services.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="idgen-client.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="idgen-service.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
