{
 "title": "main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "messages total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(messaging_messages_received)",
     "legendFormat": "received"
    },
    {
     "expr": "sum(messaging_messages_processed)",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "messages per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "messaging_messages_received",
     "legendFormat": "received (server {{messaging_server_id}})"
    },
    {
     "expr": "messaging_messages_processed",
     "legendFormat": "processed (server {{messaging_server_id}})"
    }
   ]
  },
  {
   "title": "online clients total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    { "expr": "sum(messaging_online_clients)", "legendFormat": "online clients" }
   ]
  },
  {
   "title": "online clients per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "messaging_online_clients",
     "legendFormat": "online clients (server {{messaging_server_id}})"
    }
   ]
  },
  {
   "title": "HTTP request rate / 10m",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_server_duration_ms_count[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request duration ms",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 12 },
   "targets": [
    { "expr": "http_server_duration_ms_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "history db request rate / 10m",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(historydb_query_duration_ms_count[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "history db request duration ms",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 18 },
   "targets": [
    {
     "expr": "historydb_query_duration_ms_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "state db request rate / 10m",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(statedb_query_duration_ms_count[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "state db request duration ms",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 24 },
   "targets": [
    {
     "expr": "statedb_query_duration_ms_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}