<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Common.OpenTelemetry/Common.OpenTelemetry.csproj" />
  </ItemGroup>

</Project>
