name: Containerize

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

jobs:
  containerize:
    runs-on: ubuntu-latest
    steps:

    - name: Docker Hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker setup
      uses: docker/setup-buildx-action@v1

    - name: Checkout
      uses: actions/checkout@v3

    - name: BFF image
      uses: docker/build-push-action@v2
      with:
        file: run/cecochat/Bff.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-bff:0.1

    - name: Messaging image
      uses: docker/build-push-action@v2
      with:
        file: run/cecochat/Messaging.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-messaging:0.1

    - name: State image
      uses: docker/build-push-action@v2
      with:
        file: run/cecochat/State.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-state:0.1

    - name: History image
      uses: docker/build-push-action@v2
      with:
        file: run/cecochat/History.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-history:0.1

    - name: IDGen image
      uses: docker/build-push-action@v2
      with:
        file: run/cecochat/IDGen.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-idgen:0.1

    - name: User image
      uses: docker/build-push-action@v2
      with:
        file: run/cecochat/User.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-user:0.1
