apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-kafka
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}-kafka
spec:
  selector:
    app: {{.Release.Name}}-kafka
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{.Values.Kafka.Networking.Port}}
