apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-zk
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}-zk
data:
  {{.Values.Zk.Entrypoint.ConfigName}}: |-
    #!/bin/bash
    export ZOO_MY_ID=${HOSTNAME##*-}
    /docker-entrypoint.sh zkServer.sh start-foreground
